apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: angular-15-client-tutorialsonline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angular-15-client-tutorialsonline
    app.kubernetes.io/part-of: tutorialsonline
  name: angular-15-client-tutoriabdkp
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: angular-15-client-tutorialsonline
    weight: 100
status: {}
